title: Aristotelis Pozidis
subtitle: Junior Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact Me
      url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: profile.png
author: Aristotelis Poziis
author_bio: Hello, My Name is Aristotelis Pozidis. I love to Code!
author_email: "arist.poz@gmail.com"
author_location: Greece
# author_website_url: ""

author_work_experiences:
            - company_name: Foodtec Solutions Inc.
              company_logo: foodtec.png
              company_url: https://foodtecsolutions.com/
              designation: Software Engineer
              type: Full-time
              description: //TODO
              visibility: true
            - company_name: ASML
              company_logo: asml.png
              company_url: https://www.asml.com/en
              designation: Software Desing Engineer
              type: Internship
              description: //TODO
              visibility: true

author_education_details:
              - college_logo: ihu.png
                college_name: International Hellenic University
                college_url: http://ict.ihu.gr/
                college_degree: Computer Science
                description: Bachelor of Science
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false

# social links
# twitter_username: 
github_username:  ArisPoz
facebook_username: ArisPoz
linkedin_username: AristPoz
# behance_username: 
instagram_username: Aris.Poz
# medium_username: 
# telegram_username: 
# dribbble_username: 
# flickr_username: 

#for comments using disqus
# disqus_shortname: 

# wakatime username (coding activity)
# wakatime_username: 

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: arist.poz@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build